defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[acme]
email = "letsencrypt@pointlook.com"
storageFile = "/etc/traefik/acme.json"
entryPoint = "https"
onDemand = true
OnHostRule = true

[[acme.domains]]
main = "pointlook.com"
sans = ["pl412app.pointlook.com", "echo.pointlook.com", "blog.pointlook.com", "shell.pointlook.com", "s3server.pointlook.com"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "pointlook.com"
watch = true
